#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

PATH="$PATH:/Users/janneka/bin"
PATH="$PATH:/Users/janneka/Dropbox (Personal)/bin"
PATH="$PATH:/Users/janneka/Dropbox/bin"
PATH="$PATH:/Library/Frameworks/Mono.framework/Versions/Current/bin"
PATH="$PATH:/Users/janneka/Library/Android/sdk/platform-tools"
PATH="$PATH:/Users/janneka/Library/Python/2.7/bin"
PATH="$PATH:/usr/local/go/bin"
PATH="$PATH:/Users/janneka/.cargo/bin"
export PATH

export SUBLIME=subl
export EDITOR="$SUBLIME --wait"
export VISUAL=$EDITOR
export ELIXIR_EDITOR="$SUBLIME --wait"

export LC_CTYPE=en_US.UTF-8
export BOOST_ROOT=/Users/janneka/src/lib/boost
export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.auth/homebrew_git_token)

export ANDROID_HOME=/Users/janneka/Library/Android/sdk
export ANSIBLE_VAULT_PASSWORD_FILE=/Users/janneka/.ansible_vault_password

export ERL_AFLAGS="-kernel shell_history enabled"

export GOPATH=/Users/janneka/src/go
