#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

PATH="$PATH:/Users/janneka/bin"
PATH="$PATH:/Users/janneka/Dropbox (Personal)/bin"
PATH="$PATH:/Users/janneka/Dropbox/bin"
PATH="$PATH:/Library/Frameworks/Mono.framework/Versions/Current/bin"
PATH="$PATH:/Users/janneka/Library/Android/sdk/platform-tools"
PATH="$PATH:/Users/janneka/Library/Python/2.7/bin"
PATH="$PATH:/usr/local/go/bin"
export PATH

export SUBLIME=subl
export EDITOR="$SUBLIME --wait"
export VISUAL=$EDITOR
export ELIXIR_EDITOR="$SUBLIME --wait"

export LC_CTYPE=en_US.UTF-8
export BOOST_ROOT=/Users/janneka/src/lib/boost
export HOMEBREW_GITHUB_API_TOKEN=$(cat ~/.auth/homebrew_git_token)

export DOCKER_CERT_PATH=/Users/janneka/.boot2docker/certs/boot2docker-vm
export DOCKER_TLS_VERIFY=1
export DOCKER_HOST=tcp://192.168.59.103:2376

export AWS_ACCESS_KEY_ID="$(parse_aws_credentials.py dev aws_access_key_id)"
export AWS_SECRET_ACCESS_KEY="$(parse_aws_credentials.py dev aws_secret_access_key)"
export AWS_DEFAULT_REGION=us-east-1
export AWS_ENV=dev

export ANDROID_HOME=/Users/janneka/Library/Android/sdk
export ANSIBLE_VAULT_PASSWORD_FILE=/Users/janneka/.ansible_vault_password

export ERL_AFLAGS="-kernel shell_history enabled"

export GOPATH=/Users/janneka/src/go
