#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt AUTO_NAME_DIRS
setopt AUTO_CD

function awse {
	if [[ $# == 0 ]]; then
		unset AWS_ACCESS_KEY_ID
		unset AWS_SECRET_ACCESS_KEY
		unset AWS_ENV
		echo Clearing AWS authentication
		export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_ENV
	else
		if [[ $(parse_aws_credentials.py $1) == "" ]]; then
			echo No aws profile found for env $1
		else
			AWS_ACCESS_KEY_ID=$(parse_aws_credentials.py $1 AWS_ACCESS_KEY_ID)
			AWS_SECRET_ACCESS_KEY=$(parse_aws_credentials.py $1 AWS_SECRET_ACCESS_KEY)
			AWS_ENV=$1
			echo Setting AWS authentication to env: \"$AWS_ENV\" key_id: \"$AWS_ACCESS_KEY_ID\" access_key: \"$AWS_SECRET_ACCESS_KEY[0,5]...\"
			export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_ENV
		fi
	fi
}

# Unalias things
unalias 1
unalias 2
unalias 3
unalias 4
unalias 5
unalias 6
unalias 7
unalias 8
unalias 9
unalias _
unalias b
unalias bower
unalias fc
unalias find
unalias g
unalias gCO
unalias gCT
unalias gCa
unalias gCe
unalias gCl
unalias gCo
unalias gCt
unalias gR
unalias gRa
unalias gRb
unalias gRl
unalias gRm
unalias gRp
unalias gRs
unalias gRu
unalias gRx
unalias gS
unalias gSI
unalias gSa
unalias gSf
unalias gSi
unalias gSl
unalias gSm
unalias gSs
unalias gSu
unalias gSx
unalias gb
unalias gbL
unalias gbM
unalias gbS
unalias gbX
unalias gbc
unalias gbl
unalias gbm
unalias gbs
unalias gbx
unalias gc
unalias gcF
unalias gcO
unalias gcP
unalias gcR
unalias gca
unalias gcc
unalias gcf
unalias gcl
unalias gcm
unalias gco
unalias gcp
unalias gcr
unalias gcs
unalias gd
unalias gdc
unalias gdi
unalias gdk
unalias gdm
unalias gdu
unalias gdx
unalias get
unalias gf
unalias gfc
unalias gfm
unalias gfr
unalias gg
unalias ggL
unalias ggi
unalias ggl
unalias ggv
unalias ggw
unalias giA
unalias giD
unalias giR
unalias giX
unalias gia
unalias gid
unalias gir
unalias gist
unalias giu
unalias gix
unalias gl
unalias glb
unalias glc
unalias gld
unalias glg
unalias glo
unalias gls
unalias gm
unalias gmC
unalias gmF
unalias gma
unalias gmt
unalias gp
unalias gpA
unalias gpa
unalias gpc
unalias gpf
unalias gpp
unalias gpt
unalias gr
unalias gra
unalias grc
unalias gri
unalias grs
unalias gs
unalias gsL
unalias gsS
unalias gsX
unalias gsa
unalias gsd
unalias gsl
unalias gsp
unalias gsr
unalias gss
unalias gsw
unalias gsx
unalias gwC
unalias gwD
unalias gwR
unalias gwS
unalias gwX
unalias gwc
unalias gwd
unalias gwr
unalias gws
unalias gwx
unalias heroku
unalias history-stat
unalias http-serve
unalias mysql
unalias o
unalias p
unalias pbc
unalias pbp
unalias po
unalias pu
unalias rake
unalias rsync
unalias run-help
unalias scp
unalias sftp
unalias sl
unalias type

# Aliases
alias gs='git status'