#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
setopt AUTO_NAME_DIRS
setopt AUTO_CD

source "$HOME/src/awse/awse.sh"
test -s "$HOME/.kiex/scripts/kiex" && source "$HOME/.kiex/scripts/kiex"

fpath=(/usr/local/share/zsh-completions $fpath)

# Custom alias overrides
alias j='fasd_cd'
alias rm='nocorrect rm'

# mix test doesn't understand paths
compdef -d mix
ulimit -n 4096
